name: Coverage

on:
  push:
    branches: [ dev ]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lcov gcovr make gcc

    - name: Build with coverage flags
      run: |
        make mrproper
        make tests_server

    - name: Run tests
      run: ./tests_server

    - name: Generate coverage report
      run: gcovr --root . --xml-pretty -o coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.xml
        fail_ci_if_error: true
