name: Coverage

on:
  push:
    branches: [ dev ]
    paths:
      - 'ai/**'
      - 'server/**'
      - 'gui/**'
      - 'Makefile'
      - 'tests/**'
      - '.github/workflows/cov.yml'

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
           lcov gcovr make gcc g++ \
           python3 python3-pip libglew-dev glew-utils \
           libsdl2-dev libsdl2-image-dev libglm-dev
        pip install coverage pytest pytest-cov

    - name: Clean build artifacts
      run: make mrproper

    # === Server (C) ===
    - name: Build server with coverage flags
      run: |
        make tests_server

    - name: Run server tests
      run: make tests_run_server

    - name: Generate server coverage
      run: |
        gcovr --root . --filter 'server/' --xml-pretty -o coverage-server.xml --exclude 'tests/server/'

    # === GUI (C++) ===
    - name: Build GUI with coverage flags
      run: make tests_gui

    - name: Run GUI tests
      run: make tests_run_gui

    - name: Generate GUI coverage
      run: |
        gcovr --root . --filter 'GUI/' --xml-pretty -o coverage-gui.xml --exclude 'tests/gui/'

    # === AI (Python) ===
    - name: Run AI tests and generate coverage
      run: |
        make tests_run_ai
        coverage xml -o ../coverage-ai.xml

    # === Upload All Reports to Codecov ===
    - name: Upload coverage to Codecov (server)
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage-server.xml
        flags: server
        fail_ci_if_error: true

    - name: Upload coverage to Codecov (GUI)
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage-gui.xml
        flags: gui
        fail_ci_if_error: true

    - name: Upload coverage to Codecov (AI)
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage-ai.xml
        flags: ai
        fail_ci_if_error: true
