name: Documentation

on:
  push:
    branches: [ dev ]

permissions:
  contents: write

jobs:
  doc:
    runs-on: ubuntu-latest

    steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v4

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build documentation
      run: nix build .#doc

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./result
