name: Documentation

on:
  push:
    branches: [ dev ]

jobs:
  doc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get install -y doxygen graphviz

    - name: Build doc
      run: doxygen Doxyfile

    - name: Upload doc to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        force_orphan: true
        deploy_key: ${{ secrets.GH_SSH_PRIVATE_KEY }}
        publish_dir: ./.doc/html
